// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxojtuwdhhiybitxuqjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b2p0dXdkaGhpeWJpdHh1cWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDgxMjMsImV4cCI6MjA1ODA4NDEyM30.wPZBEnbzg6FSRcT_YFeGVWPb2hA-4w6XmfdeIvJhAZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);